"""users table

Revision ID: 9ec2ee64e18b
Revises: 9221f4fbd49c
Create Date: 2023-02-18 14:14:09.203344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec2ee64e18b'
down_revision = '9221f4fbd49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkpoint_current', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('checkpoint_current')

    # ### end Alembic commands ###
