"""users table

Revision ID: f26f3ccf54b4
Revises: a776d0cd38d4
Create Date: 2023-02-18 04:44:19.283111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26f3ccf54b4'
down_revision = 'a776d0cd38d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
